name: Wails build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'GenieAlogy-linux-amd64'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'GenieAlogy-windows-amd64.exe'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'GenieAlogy-darwin-universal.app'
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: 1.24.0

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Linux dependencies
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libglib2.0-dev \
            pkg-config

      - name: Build
        run: |
          if [[ "${{ matrix.build.os }}" == "ubuntu-latest" ]]; then
            wails build --platform ${{ matrix.build.platform }} -tags webkit2_41
            mv build/bin/GenieAlogy build/bin/${{ matrix.build.name }}
          elif [[ "${{ matrix.build.os }}" == "macos-latest" ]]; then
            wails build --platform ${{ matrix.build.platform }}
            mv build/bin/GenieAlogy.app build/bin/${{ matrix.build.name }}
          elif [[ "${{ matrix.build.os }}" == "windows-latest" ]]; then
            wails build --platform ${{ matrix.build.platform }}
            mv build/bin/GenieAlogy.exe build/bin/${{ matrix.build.name }}
          fi
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.platform }}
          path: build/bin/*