name: Produce GenieAlogy builds

on:
  workflow_dispatch:
    inputs:
      version:
        description: Build GenieAlogy
        required: true

jobs:
  test:
    name: "Build application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.0
      - name: Build MacOS (AMD64)
        run: wails build --platform darwin/amd64
      - name: Build MacOS (ARM64)
        run: wails build --platform darwin/arm64

      - name: Build Linux (AMD64)
        run: wails build --platform linux/amd64
      - name: Build Linux (ARM64)
        run: wails build --platform linux/arm64

      - name: Build Windows (AMD64)
        run: wails build --platform windows/amd64
      - name: Build Windows (ARM64)
        run: wails build --platform windows/arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geniealogy-build-${{ github.event.inputs.version }}
          path: |
            build/bin/*