name: Run audits

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: "Run audits"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - uses: actions/setup-go@v6
        with:
          go-version: 1.24.0

      - name: Run tests
        run: |
          cd frontend
          npm audit
          go run tool golang.org/x/vuln/cmd/govulncheck ./...